# Generated by Django 2.0 on 2017-12-07 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklist', '0003_auto_20171207_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeid',
            name='aladin_id',
            field=models.CharField(blank=True, default='aladin', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeid',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 7, 14, 50, 28, 412592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storeid',
            name='ridibooks_id',
            field=models.CharField(blank=True, default='ridibooks', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeid',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 7, 14, 50, 28, 412535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storeid',
            name='yes24_id',
            field=models.CharField(blank=True, default='yes24', max_length=20),
        ),
    ]
